version: "3.9"
services:

  redis:
    image: "redis:alpine"
    depends_on:
      - postgres
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d main_db"]
      interval: 5s
      timeout: 5s
      retries: 5